# Generated by Django 4.1.13 on 2024-03-06 19:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('address_one', models.CharField(default='', max_length=300)),
                ('address_two', models.CharField(default='', max_length=300)),
                ('city', models.CharField(default='', max_length=200)),
                ('province', models.CharField(default='', max_length=200)),
                ('postal_code', models.CharField(default=0, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'MasterCard'), ('AMERICAN EXPRESS', 'American Express'), ('OTRO', 'Otro')], default='VISA', max_length=20)),
                ('titular', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=255)),
                ('mes_caducidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('anio_caducidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2999)])),
                ('codigo_seguridad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)])),
            ],
            options={
                'verbose_name_plural': 'Tarjetas',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('vip', models.BooleanField(default=False)),
                ('direcciones', models.ManyToManyField(blank=True, related_name='clientes', to='main.direccion')),
                ('tarjetas', models.ManyToManyField(blank=True, related_name='clientes', to='main.tarjeta')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
