# Generated by Django 4.1.13 on 2024-03-06 19:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('unidades', models.PositiveIntegerField()),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('iva', models.DecimalField(decimal_places=2, default=0.21, max_digits=2)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.cliente')),
                ('direccion_envio', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='compras_envio', to='main.direccion')),
                ('direccion_facturacion', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='compras_facturacion', to='main.direccion')),
                ('tarjeta', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.tarjeta')),
            ],
            options={
                'verbose_name_plural': 'Compras',
                'ordering': ['cliente'],
                'unique_together': {('cliente', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=250)),
                ('nombre', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('unidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('vip', models.BooleanField(default=False)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.marca')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'unique_together': {('marca', 'modelo')},
            },
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('puntuacion', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.producto')),
            ],
            options={
                'verbose_name_plural': 'Comentarios',
            },
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.producto')),
            ],
            options={
                'verbose_name_plural': 'Items Carrito',
            },
        ),
    ]
